app = "eventosm-redis"

[mounts]
  destination = "/data"
  source = "eventosm_redis_store"

[build]
  image = "flyio/redis:6.2.6"

[[services]]
internal_port = 6379
protocol      = "tcp"

  [[services.ports]]
  port     = "10000"

  [[services.tcp_checks]]
  interval = 10000
  timeout  = 2000